import os
from datetime import datetime

class list_files:
	'''
	LIST_FILES CLASS CONTAINS TWO FUNCTIONS:
	1) __INIT__
	2) WORK()
	
	INIT BLOCK DOCKINFO :
		INIT BLOCK INITIATES TWO VARIABLES 'ALL_DATA' WHICH IS A LIST THAT WILL CONTAIN ALL THE FETCHED FILES LATER and IT ALSO CONTAINS 'COUNT' WHICH KEEPS 
		RECORD FOR THE NUMBER OF FILES.

	WORK() FUNCTION DOCINFO: 
		1) WORK FUNCTION IS THE MAIN FUNCTION OF CLASS WHICH FINDS ALL THE FILES AND GIVES THE OUTPUT IN FILE "File Found.csv" IN SAME DIRECTORY AS IN SCRIPT
		RESIDES,
		2) IT RETURNS NUMBER OF FILES FOUND AS A RETURN VALUE. 		
	'''
	def __init__(self):
		'''
		INIT BLOCK DOCKINFO :
		INIT BLOCK INITIATES TWO VARIABLES 'ALL_DATA' WHICH IS A LIST THAT WILL CONTAIN ALL THE FETCHED FILES LATER and IT ALSO CONTAINS 'COUNT' WHICH KEEPS 
		RECORD FOR THE NUMBER OF FILES.
		'''
		self.all_data = []
		self.count = 0

	def work(self):
		'''
		WORK() FUNCTION DOCINFO: 
		1) WORK FUNCTION IS THE MAIN FUNCTION OF CLASS WHICH FINDS ALL THE FILES AND GIVES THE OUTPUT IN FILE "File Found.csv" IN SAME DIRECTORY AS IN SCRIPT
		RESIDES,
		2) IT RETURNS NUMBER OF FILES FOUND AS A RETURN VALUE. 
		'''
		for (root, dirs, files) in os.walk("/", topdown=True):		# FINDING ALL FIES IN ROOT DIRECTORY
			file_list = [file+","+root+file for file in files]		# MODIFYING FILE LIST ACCORDING TO REQUIRED FORMAT
			self.all_data.extend(file_list)							# SAVING ALL FILES FOUND IN CURRENT DIRECTORY INTO ALL_DATA LIST WHICH IS GLOBAL LIST FOR ALL FILES		
			self.count += len(file_list)							# INCREASING COUNT BY THE SAME NUMBER OF FILES, FOUND IN CURRENT DIRECTORY

		data = "File Name, File Address\n"							# INITIAL SETUP FOR DATA VARIABLE WHICH WILL STORE ALL FILE NAME IN FORMATTED WAY
		data += '\n'.join(self.all_data)							# ADDING FILES DATA INTO DATA VARIABLE SO THAT IT CAN BE WRITTEN DIRECTLY
		with open("File Found.csv", "w") as output:					# OOPENING FILE TO BE WRITTEN IN WRITE MODE
			output.write(data)										# DATA VARIABLE IS WRITTEN HERE INTO FILE
		return self.count 											# RETURNING COUNT VARIABLE I.E. NUMBER OF FILES FOUND IN ROOT DIRECTORY
