import os
import re

class get_ports:
	'''
	********* THIS SCRIPT RETURNS A LIST OF TUPLE CONTAINING PORTS AND PROTOCOLS OPEN ON USER'S LINUX SYSTEM *********
	CLASS get_ports DOCINFO:
	get_ports HAVE TWO FUNCTIONS I.E.,
	1) __init__
	2) work()

		__init__ DOCFILE:
			__init__ BLOCK SERVES THE INITIALIZATION FUNCTION, CONTAINING INITIALIZED VARIABLES WHICH IS GOING TO BE USED LATER BY OTHER MEMBER FUNCTION.

		WORK() DOCFILE:
		1) COLLECTS DATA FROM COMMANDLINE INTO STRING AND THEN SPLITTS INTO THE LIST.
		2) TRAVERSES ON EVERY OUTPUT.
		3) EXTRACTS ALL PORTS IN OUTPUT LINE.
		4) CHECKS IF EXTRACTED PORTS COUNT IS GREATER THAN OR EQUAL TO 0.
		5) REMOVS SEMI-COLON(:) FROM THE START OF PORT.
		6) CHECKS IF THE EXTRACTED PORT EXIST BEFORE IN LIST.
		7) EXTRACTS PROTOCOL FROM THE OUTPUT.
		8) SAVES THE PROTOCOL AND PORT IN THE LIST.
		9) SAVES THE PROTOCOL IN SECONDARY LIST FOR LATER COMPARISION.
		10) RETURNS THE FINAL OUTPUT.
	'''

	def __init__(self):
		'''
__init__ DOCFILE:
__init__ BLOCK SERVES THE INITIALIZATION FUNCTION, CONTAINING INITIALIZED VARIABLES WHICH IS GOING TO BE USED LATER BY OTHER MEMBER FUNCTION.
		'''
		self.data = []																					# TO SAVE DATA RECIEVED FROM COMMAND INTO A STRING
		self.final_output = []																			# FOR SAVING BROWSER DATA COLLECTED INTO A SINGLE VARIABLE
		self.secondary_port_list = []																	# FOR SAVING ALL PORTS FOR LATER COMPARISION FOR DUPLICATE PORTS
		self.protocol = ""																				# FOR EXTRACTING PROTOCOLS FROM ALL OUTPUTS
		

	def work(self):
		'''
WORK() DOCFILE:
	THE FUNCTION WORKS IN FOLLOWING WAY:
		1) COLLECTS DATA FROM COMMANDLINE INTO STRING AND THEN SPLITTS INTO THE LIST.
		2) TRAVERSES ON EVERY OUTPUT.
		3) EXTRACTS ALL PORTS IN OUTPUT LINE.
		4) CHECKS IF EXTRACTED PORTS COUNT IS GREATER THAN OR EQUAL TO 0.
		5) REMOVS SEMI-COLON(:) FROM THE START OF PORT.
		6) CHECKS IF THE EXTRACTED PORT EXIST BEFORE IN LIST.
		7) EXTRACTS PROTOCOL FROM THE OUTPUT.
		8) SAVES THE PROTOCOL AND PORT IN THE LIST.
		9) SAVES THE PROTOCOL IN SECONDARY LIST FOR LATER COMPARISION.
		10) RETURNS THE FINAL OUTPUT.
		'''
		data = os.popen("ss -lntu").read().split('\n')													# COLLECTING DATA FROM COMMANDLINE INTO STRING AND THEN SPLITTING INTO THE LIST
		for i in data:																					# TRAVERSING ON EVERY OUTPUT
			self.ports_in_line = re.findall(r':\d{1,5}', i)												# EXTRACTING ALL PORTS IN OUTPUT LINE
			if len(self.ports_in_line) > 0 :															# CHECKING IF EXTRACTED PORTS COUNT IS GREATER THAN OR EQUAL TO 0
				self.extracted_port = self.ports_in_line[0][1:]											# REMOVING SEMI-COLON(:) FROM THE START OF PORT
				if self.extracted_port not in self.secondary_port_list:									# CHECKING IF THE EXTRACTED PORT EXIST BEFORE IN LIST
					self.protocol = i[:i.find(' ')]														# EXTRACTING PROTOCOL FROM THE OUTPUT
					self.final_output.append((self.protocol,self.extracted_port))						# SAVING THE PROTOCOL AND PORT IN THE LIST
					self.secondary_port_list.append(self.extracted_port)								# SAVING THE PROTOCOL IN SECONDARY LIST FOR LATER COMPARISION
		return self.final_output																		# RETURNING THE FINAL OUTPUT